### ISSUE TITLE
Data from large files is not returned

### ISSUE THREAD

**Issue by hgardneriv** [half-metal/frontend-sveltekit-lumberjill#2]
When testing with a file around 45 MB no output is returned. The backend app seems to restart and the UI eventually locks up. Tested with a file around 10 MB and it worked but output was slow to be displayed in the UI. _Ideally_ the project should be able to handle large files.

**Comment by half-metal** [comment]
Yes, it's using fs.readFile instead of a stream, which loads that into entire file into memory. When I have some time I'll update this to use streaming which should handle files greater > 10 MB.

**Comment by hgardneriv** [comment]
Another recommendation would be to modify the way the file is processed. An optimal approach is to open file, seek to end, read file backward in chunks, and stream results. Only return the number of matching results requested (default  to 10). One of the tests we typically run is to attempt to process a 1.5 GB file.

**Comment by half-metal** [comment]
That makes sense to read file backwards, and I can make a default + configurable value to return number of matching results. Yes this should handle 1.5 GB and larger file, I already have a file for that to verify with.

**Comment by half-metal** [comment]
Sveltekit has limitation atm with streaming that they have an open issue for that I am tracking. In the meantime, the Node backend handles large files fine via readStream, transform, pipe https://github.com/half-metal/lumberjill-backend-node and I've updated the Readme to indicate that should be used.

Currently, I have configured a setting threshold for ~400mb in hyperStream.js in the node backend
`const fileSizeThreshold = 411451157 //411mb`
 so that this frontend can display the logs. Even though I am using a virtual list with Sveltekit, the browser gets slow or doesn't load over 400mb, so I've limited it to ~400mb. I'm planning on an enhancement with Infinite Scroll which would allow doing API calls as it reaches the index of lines that indicates the browser is ready to load new batch of data. https://github.com/andrelmlins/svelte-infinite-scroll. Below is an image showing the call which is just calling the node backend https://github.com/half-metal/lumberjill-backend-node, this takes 2-5 seconds for a 411mb file on frontend calling the node backend on same machine.

![image](https://user-images.githubusercontent.com/58837299/169967106-28490268-0abe-4535-adf1-5b0d569bc890.png)
